packages:
  # - 'apps/*' # It seems you don't have an apps directory
  - 'packages/*'
  # - 'tooling/*' # It seems you don't have a tooling directory
  # exclude discord-scrapper

# Default catalog for common dependencies
catalog:
  # React ecosystem
  react: ^19.0.0
  react-dom: ^19.0.0
  "@radix-ui/react-tabs": ^1.1.3
  "@radix-ui/react-separator": ^1.1.2
  "@types/react": ^18.2.0
  "@types/react-dom": ^18.2.0
  next: ^15.3.3
  eslint-config-next: ^15.3.3

  # Testing
  "@playwright/test": ^1.51.0

# Forms
  react-hook-form: ^7.53.0
  "@hookform/resolvers": ^3.9.0

  # Auth
  "@auth/core": ^0.37.2
  "@auth/drizzle-adapter": ^1.7.4
  next-auth: ^5.0.0-beta.25

  # Development tools
  typescript: ^5.6.3
  eslint: ^8.57.0
  prettier: ^3.0.0
  tailwindcss: ^3.4.1
  postcss: ^8.0.0
  autoprefixer: ^10.4.20

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.25.0
  "@trpc/client": ^11.0.0
  "@trpc/server": ^11.0.0
  "@trpc/react-query": ^11.0.0
  "@trpc/next": ^11.0.0
  "@trpc/tanstack-react-query": ^11.0.0

  # UI Components
  class-variance-authority: ^0.7.1
  "@radix-ui/react-dialog": ^1.0.5
  "@radix-ui/react-label": ^2.0.2
  "@radix-ui/react-slot": ^1.0.2
  "@radix-ui/react-tooltip": ^1.0.7
  # The user's selection indicates multiple versions of dropdown menu, let's pin it here
  "@radix-ui/react-dropdown-menu": ^2.0.6
  # The user's selection indicates multiple versions of select, let's pin it here
  "@radix-ui/react-select": ^2.0.0 # Adding select as it seems to be causing issues based on the error log
  framer-motion: ^11.3.19
  geist: ^1.3.1
  lucide-react: ^0.476.0
  next-themes: ^0.3.0
  sonner: ^2.0.1
  tailwind-merge: ^3.0.2

  # AI SDK
  "@ai-sdk/react": "^1.2.12"
  "@ai-sdk/openai": "1.3.22"
  ai: "^4.1.0"

  # Database & Storage
  "@vercel/blob": ^0.27.3
  dotenv: ^16.4.7
  drizzle-orm: ^0.38.3
  drizzle-kit: ^0.30.1

  # Utils
  zod: ^3.25.0
  zustand: ^5.0.3
  tsx: ^4.19.2
  "@types/node": ^22.10.10

# Named catalogs
catalogs:
  # Request Network dependencies
  request:
    "@requestnetwork/epk-cipher": ^0.9.0
    "@requestnetwork/epk-signature": ^0.9.9
    "@requestnetwork/payment-processor": ^0.56.0
    "@requestnetwork/request-client.js": ^0.58.0
    "@requestnetwork/types": ^0.53.0
    "@requestnetwork/utils": ^0.53.0
    "@requestnetwork/web3-signature": ^0.8.9