export const contractors = [
  {
    id: '1',
    name: 'Sarah Chen',
    role: 'Designer & Developer',
    email: 'sarah@techstudio.io',
    company: 'Tech Studio',
    typicalInvoice: '$5,000 - $8,000 USDC',
    frequency: 'Monthly',
    lastPaid: '2024-01-15',
    totalPaid: '$45,000 USDC',
    autoPayEnabled: true,
    autoPayLimit: '$10,000 USDC',
  },
  {
    id: '2',
    name: 'Marcus Rodriguez',
    role: 'Backend Engineer',
    email: 'marcus@devhouse.com',
    company: 'DevHouse Solutions',
    typicalInvoice: '$12,000 USDC',
    frequency: 'Bi-weekly',
    lastPaid: '2024-01-10',
    totalPaid: '$156,000 USDC',
    autoPayEnabled: true,
    autoPayLimit: '$15,000 USDC',
  },
  {
    id: '3',
    name: 'Emma Thompson',
    role: 'Content Strategist',
    email: 'emma@contentpro.co',
    company: 'ContentPro Agency',
    typicalInvoice: '$3,500 USDC',
    frequency: 'Project-based',
    lastPaid: '2024-01-05',
    totalPaid: '$28,000 USDC',
    autoPayEnabled: false,
  },
  {
    id: '4',
    name: 'Alex Kim',
    role: 'Mobile Developer',
    email: 'alex@appcrafters.io',
    company: 'AppCrafters',
    typicalInvoice: '$7,500 USDC',
    frequency: 'Monthly',
    lastPaid: '2023-12-28',
    totalPaid: '$67,500 USDC',
    autoPayEnabled: true,
    autoPayLimit: '$8,000 USDC',
  },
];

export const recentPayments = [
  {
    id: '1',
    contractor: 'Sarah Chen',
    amount: '$5,000 USDC',
    date: '2024-01-18',
    invoice: 'Website Redesign',
    status: 'completed',
    receipt: 'PAY-2024-089',
  },
  {
    id: '2',
    contractor: 'Marcus Rodriguez',
    amount: '$12,000 USDC',
    date: '2024-01-15',
    invoice: 'API Development Sprint 4',
    status: 'completed',
    receipt: 'PAY-2024-088',
  },
  {
    id: '3',
    contractor: 'Emma Thompson',
    amount: '$3,500 USDC',
    date: '2024-01-12',
    invoice: 'Q1 Content Strategy',
    status: 'completed',
    receipt: 'PAY-2024-087',
  },
];

export const upcomingPayments = [
  {
    id: '1',
    contractor: 'Alex Kim',
    amount: '$7,500 USDC',
    dueDate: '2024-02-01',
    invoice: 'Mobile App v2.0',
    autoPayScheduled: true,
    scheduledTime: '10:00 AM',
  },
  {
    id: '2',
    contractor: 'Marcus Rodriguez',
    amount: '$12,000 USDC',
    dueDate: '2024-02-05',
    invoice: 'API Development Sprint 5',
    autoPayScheduled: true,
    scheduledTime: '10:00 AM',
  },
];